DROP DATABASE IF EXISTS burgers_db;

CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers(
id INT AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(1000),
devoured BOOLEAN DEFAULT FALSE,
date TIMESTAMP,
PRIMARY KEY(id)
);